using System.Text.Json;
using SemanaIA.ServiceInvoice.Domain.Models;
using SemanaIA.ServiceInvoice.Domain.Repositories;
using SemanaIA.ServiceInvoice.Domain.Services;
using SemanaIA.ServiceInvoice.XmlGeneration.SchemaEngine;

namespace SemanaIA.ServiceInvoice.Application;

public class ProviderManagementService
{
    private readonly IProviderRepository _repository;
    private readonly IProviderValidator _validator;

    public ProviderManagementService(IProviderRepository repository, IProviderValidator validator)
    {
        _repository = repository;
        _validator = validator;
    }

    public async Task<ProviderManagementResult> Create(
        string name,
        List<XsdFileEntry> xsdFiles,
        List<string>? municipalityCodes = null,
        string? primaryXsdFile = null)
    {
        if (string.IsNullOrWhiteSpace(name))
            return ProviderManagementResult.ValidationError("Provider name is required.");

        if (xsdFiles.Count == 0)
            return ProviderManagementResult.ValidationError("At least one XSD file is required.");

        var existingProvider = await _repository.GetByName(name);
        if (existingProvider is not null)
            return ProviderManagementResult.Conflict($"A provider with name '{name}' already exists.");

        if (municipalityCodes is { Count: > 0 })
        {
            var municipalityConflicts = await _repository.FindProvidersByMunicipalityCodes(municipalityCodes);
            if (municipalityConflicts.Count > 0)
                return BuildMunicipalityConflictResult(municipalityConflicts);
        }

        var provider = ManagedProvider.Create(name, xsdFiles, municipalityCodes);

        if (primaryXsdFile is not null)
            provider.UpdatePrimaryXsdFile(primaryXsdFile);

        // Auto-gerar regras default a partir do XSD
        var autoGeneratedRules = AutoGenerateRules(provider);
        if (autoGeneratedRules.Rules.Count > 0)
        {
            var profile = autoGeneratedRules.Profile;
            profile.Rules = autoGeneratedRules.Rules;
            var rulesJson = System.Text.Json.JsonSerializer.Serialize(profile);
            provider.UpdateRulesJson(rulesJson);

            if (profile.RootComplexTypeName is not null)
                provider.UpdatePrimaryXsdFile(provider.PrimaryXsdFile ?? primaryXsdFile);
        }

        await _repository.Save(provider);

        return ProviderManagementResult.Success(provider);
    }

    public async Task<ProviderManagementResult> Update(
        string id,
        string? name = null,
        List<XsdFileEntry>? xsdFiles = null,
        string? primaryXsdFile = null,
        string? version = null)
    {
        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderManagementResult.NotFound(id);

        if (name is not null && name != provider.Name)
        {
            var existingProvider = await _repository.GetByName(name);
            if (existingProvider is not null)
                return ProviderManagementResult.Conflict($"A provider with name '{name}' already exists.");

            provider.UpdateName(name);
        }

        if (xsdFiles is not null)
            provider.UpdateXsdFiles(xsdFiles);

        if (primaryXsdFile is not null)
            provider.UpdatePrimaryXsdFile(primaryXsdFile);

        if (version is not null)
            provider.UpdateVersion(version);

        var validationResult = await _validator.Validate(provider);
        provider.RecordValidation(validationResult);

        await _repository.Save(provider);

        return ProviderManagementResult.Success(provider);
    }

    public async Task<ManagedProvider?> Get(string id)
    {
        return await _repository.GetById(id);
    }

    public async Task<List<ManagedProvider>> List(ProviderStatus? statusFilter = null)
    {
        return await _repository.List(statusFilter);
    }

    public async Task<ProviderManagementResult> Delete(string id)
    {
        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderManagementResult.NotFound(id);

        await _repository.Delete(id);

        return ProviderManagementResult.Success(provider);
    }

    public async Task<ProviderManagementResult> Activate(string id)
    {
        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderManagementResult.NotFound(id);

        if (provider.ValidationHistory.Count == 0)
        {
            var validationResult = await _validator.Validate(provider);
            provider.RecordValidation(validationResult);
        }
        else
        {
            provider.Activate();
        }

        await _repository.Save(provider);

        return ProviderManagementResult.Success(provider);
    }

    public async Task<ProviderManagementResult> Deactivate(string id)
    {
        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderManagementResult.NotFound(id);

        provider.Deactivate();
        await _repository.Save(provider);

        return ProviderManagementResult.Success(provider);
    }

    public async Task<ProviderManagementResult> Validate(string id)
    {
        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderManagementResult.NotFound(id);

        var validationResult = await _validator.Validate(provider);
        provider.RecordValidation(validationResult);
        await _repository.Save(provider);

        return ProviderManagementResult.Success(provider);
    }

    public async Task<ProviderManagementResult> AddMunicipalities(string id, List<string> codes)
    {
        if (codes.Count == 0)
            return ProviderManagementResult.ValidationError("At least one municipality code is required.");

        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderManagementResult.NotFound(id);

        var municipalityConflicts = await _repository.FindProvidersByMunicipalityCodes(codes, excludeProviderId: id);
        if (municipalityConflicts.Count > 0)
            return BuildMunicipalityConflictResult(municipalityConflicts);

        provider.AddMunicipalities(codes);
        await _repository.Save(provider);

        return ProviderManagementResult.Success(provider);
    }

    public async Task<ProviderManagementResult> RemoveMunicipalities(string id, List<string> codes)
    {
        if (codes.Count == 0)
            return ProviderManagementResult.ValidationError("At least one municipality code is required.");

        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderManagementResult.NotFound(id);

        provider.RemoveMunicipalities(codes);
        await _repository.Save(provider);

        return ProviderManagementResult.Success(provider);
    }

    public async Task<ProviderRulesResult> GetRules(string id)
    {
        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderRulesResult.NotFound(id);

        var rules = DeserializeRules(provider.RulesJson);
        return ProviderRulesResult.Success(rules);
    }

    public async Task<ProviderRulesResult> ReplaceRules(string id, List<ProviderRule> rules)
    {
        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderRulesResult.NotFound(id);

        var validationErrors = new ProviderRuleValidator().Validate(rules);
        if (validationErrors.Count > 0)
            return ProviderRulesResult.ValidationError(validationErrors);

        var serializedRules = SerializeRules(rules);
        provider.UpdateRulesJson(serializedRules);
        await _repository.Save(provider);

        return ProviderRulesResult.Success(rules);
    }

    public async Task<ProviderRulesResult> AddRules(string id, List<ProviderRule> newRules)
    {
        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderRulesResult.NotFound(id);

        var existingRules = DeserializeRules(provider.RulesJson);
        existingRules.AddRange(newRules);

        var validationErrors = new ProviderRuleValidator().Validate(existingRules);
        if (validationErrors.Count > 0)
            return ProviderRulesResult.ValidationError(validationErrors);

        var serializedRules = SerializeRules(existingRules);
        provider.UpdateRulesJson(serializedRules);
        await _repository.Save(provider);

        return ProviderRulesResult.Success(existingRules);
    }

    public async Task<ProviderRulesResult> RemoveRule(string id, int index)
    {
        var provider = await _repository.GetById(id);
        if (provider is null)
            return ProviderRulesResult.NotFound(id);

        var rules = DeserializeRules(provider.RulesJson);

        if (index < 0 || index >= rules.Count)
            return ProviderRulesResult.IndexOutOfRange(index, rules.Count);

        rules.RemoveAt(index);

        var serializedRules = SerializeRules(rules);
        provider.UpdateRulesJson(serializedRules);
        await _repository.Save(provider);

        return ProviderRulesResult.Success(rules);
    }

    // --- Private methods ---

    private static ProviderManagementResult BuildMunicipalityConflictResult(List<MunicipalityConflict> conflicts)
    {
        var conflictDetails = string.Join(", ",
            conflicts.Select(conflict => $"'{conflict.Code}' is already assigned to provider '{conflict.ProviderName}'"));

        return ProviderManagementResult.Conflict($"Municipality code conflict: {conflictDetails}");
    }

    private static List<ProviderRule> DeserializeRules(string? rulesJson)
    {
        if (string.IsNullOrWhiteSpace(rulesJson))
            return [];

        try
        {
            var profile = JsonSerializer.Deserialize<ProviderProfile>(rulesJson);
            return profile?.Rules ?? [];
        }
        catch
        {
            return [];
        }
    }

    private static string SerializeRules(List<ProviderRule> rules)
    {
        var profile = new ProviderProfile { Rules = rules };
        return JsonSerializer.Serialize(profile);
    }

    private static (List<ProviderRule> Rules, ProviderProfile Profile, List<string> MissingFields) AutoGenerateRules(
        ManagedProvider provider)
    {
        string? tempDir = null;
        try
        {
            tempDir = Path.Combine(Path.GetTempPath(), $"provider-autogen-{provider.Id}-{Guid.NewGuid():N}");
            var xsdDir = Path.Combine(tempDir, "xsd");
            Directory.CreateDirectory(xsdDir);

            foreach (var xsdFile in provider.XsdFiles)
                File.WriteAllBytes(Path.Combine(xsdDir, xsdFile.FileName), xsdFile.Content);

            return ProviderConfigGenerator.GenerateFromXsdFiles(xsdDir, provider.Name, provider.PrimaryXsdFile);
        }
        catch
        {
            return ([], new ProviderProfile { Provider = provider.Name }, []);
        }
        finally
        {
            if (tempDir is not null && Directory.Exists(tempDir))
                try { Directory.Delete(tempDir, true); } catch { }
        }
    }
}

public record ProviderManagementResult(
    bool IsSuccess,
    ManagedProvider? Provider,
    string? ErrorMessage = null,
    ProviderManagementErrorKind ErrorKind = ProviderManagementErrorKind.None)
{
    public static ProviderManagementResult Success(ManagedProvider provider) =>
        new(true, provider);

    public static ProviderManagementResult NotFound(string id) =>
        new(false, null, $"Provider with id '{id}' not found.", ProviderManagementErrorKind.NotFound);

    public static ProviderManagementResult Conflict(string message) =>
        new(false, null, message, ProviderManagementErrorKind.Conflict);

    public static ProviderManagementResult ValidationError(string message) =>
        new(false, null, message, ProviderManagementErrorKind.ValidationError);
}

public enum ProviderManagementErrorKind
{
    None,
    NotFound,
    Conflict,
    ValidationError
}

public record ProviderRulesResult(
    bool IsSuccess,
    List<ProviderRule>? Rules,
    string? ErrorMessage = null,
    ProviderManagementErrorKind ErrorKind = ProviderManagementErrorKind.None,
    List<RuleValidationError>? RuleValidationErrors = null)
{
    public static ProviderRulesResult Success(List<ProviderRule> rules) =>
        new(true, rules);

    public static ProviderRulesResult NotFound(string id) =>
        new(false, null, $"Provider with id '{id}' not found.", ProviderManagementErrorKind.NotFound);

    public static ProviderRulesResult ValidationError(List<RuleValidationError> errors) =>
        new(false, null,
            $"Rule validation failed: {string.Join("; ", errors.Select(ruleError => $"[{ruleError.RuleDescription}] {ruleError.Message}"))}",
            ProviderManagementErrorKind.ValidationError,
            errors);

    public static ProviderRulesResult IndexOutOfRange(int index, int ruleCount) =>
        new(false, null,
            $"Rule index {index} is out of range. Provider has {ruleCount} rules (valid indices: 0 to {ruleCount - 1}).",
            ProviderManagementErrorKind.ValidationError);
}
