using SemanaIA.ServiceInvoice.XmlGeneration.SchemaEngine;
using Shouldly;

namespace SemanaIA.ServiceInvoice.UnitTests.SchemaEngine;

/// <summary>
/// Integration tests that validate ConditionalEmission rules auto-generated by
/// ProviderConfigGenerator from real XSD schemas. Ensures that CPF/CNPJ choice groups
/// and optional HasValue rules are correctly inferred and do not conflict with existing
/// hand-crafted rules.
/// </summary>
public class ConditionalEmissionAutoGenIntegrationTests
{
    // ==========================================================
    // Nacional schema -- CPF/CNPJ choice rules for toma context
    // ==========================================================

    [Fact]
    public void Given_NacionalSchema_Should_GenerateCpfCnpjConditionalRulesForToma()
    {
        // Arrange
        var xsdDir = TestProviderPaths.FindXsdDir("nacional");

        // Act
        var (rules, _, _) = ProviderConfigGenerator.GenerateFromXsdFiles(xsdDir, "nacional");

        // Assert
        var conditionalRules = rules
            .Where(r => r.Type == RuleType.ConditionalEmission)
            .ToList();
        conditionalRules.ShouldNotBeEmpty("Nacional auto-gen should produce ConditionalEmission rules");

        // There should be a CNPJ conditional rule for the toma (borrower) context
        var tomaCnpjRule = conditionalRules.FirstOrDefault(r =>
            r.Target.Contains("toma", StringComparison.OrdinalIgnoreCase) &&
            r.Target.Contains("CNPJ", StringComparison.OrdinalIgnoreCase));
        tomaCnpjRule.ShouldNotBeNull(
            "Should have a ConditionalEmission rule for toma.CNPJ. " +
            $"Available targets: {string.Join(", ", conditionalRules.Select(r => r.Target))}");
        tomaCnpjRule!.Action.ShouldBe(RuleAction.Emit);
        tomaCnpjRule.Condition.ShouldNotBeNull();
        tomaCnpjRule.Condition!.Field.ShouldBe("Borrower.FederalTaxNumber");
        tomaCnpjRule.Condition.Operator.ShouldBe(ComparisonOperator.GreaterThan);
        tomaCnpjRule.Condition.Value.ShouldBe("99999999999");
        tomaCnpjRule.PadLeft.ShouldBe(14);
        tomaCnpjRule.PadChar.ShouldBe("0");

        // There should be a CPF conditional rule for the toma (borrower) context
        var tomaCpfRule = conditionalRules.FirstOrDefault(r =>
            r.Target.Contains("toma", StringComparison.OrdinalIgnoreCase) &&
            r.Target.EndsWith("CPF", StringComparison.OrdinalIgnoreCase));
        tomaCpfRule.ShouldNotBeNull(
            "Should have a ConditionalEmission rule for toma.CPF. " +
            $"Available targets: {string.Join(", ", conditionalRules.Select(r => r.Target))}");
        tomaCpfRule!.Action.ShouldBe(RuleAction.Emit);
        tomaCpfRule.Condition.ShouldNotBeNull();
        tomaCpfRule.Condition!.IsComposite.ShouldBeTrue("CPF rule should use composite AND condition");
        tomaCpfRule.Condition.LogicalOperator.ShouldBe(LogicalOperator.And);
        tomaCpfRule.Condition.Conditions!.Count.ShouldBe(2);
        tomaCpfRule.PadLeft.ShouldBe(11);
        tomaCpfRule.PadChar.ShouldBe("0");
    }

    // ==========================================================
    // Nacional schema -- HasValue rules for optional fields
    // ==========================================================

    [Fact]
    public void Given_NacionalSchema_Should_GenerateHasValueRulesForOptionalFields()
    {
        // Arrange
        var xsdDir = TestProviderPaths.FindXsdDir("nacional");

        // Act
        var (rules, _, _) = ProviderConfigGenerator.GenerateFromXsdFiles(xsdDir, "nacional");

        // Assert
        var hasValueRules = rules
            .Where(r => r.Type == RuleType.ConditionalEmission &&
                        r.Condition?.Operator == ComparisonOperator.HasValue)
            .ToList();
        hasValueRules.ShouldNotBeEmpty(
            "Nacional auto-gen should produce HasValue ConditionalEmission rules for optional fields with known mappings");

        // Each HasValue rule should have Source and Condition.Field pointing to the same field
        foreach (var rule in hasValueRules)
        {
            rule.Source.ShouldNotBeNullOrWhiteSpace(
                $"HasValue rule for '{rule.Target}' should have a Source");
            rule.Condition!.Field.ShouldNotBeNullOrWhiteSpace(
                $"HasValue rule for '{rule.Target}' should have a Condition.Field");
            rule.Condition.Field.ShouldBe(rule.Source,
                $"HasValue rule for '{rule.Target}': Condition.Field should match Source");
            rule.Action.ShouldBe(RuleAction.Emit);
        }
    }

    // ==========================================================
    // Nacional schema -- no duplicate rules for same target
    // ==========================================================

    [Fact]
    public void Given_NacionalSchema_Should_NotDuplicateRulesForSameTarget()
    {
        // Arrange
        var xsdDir = TestProviderPaths.FindXsdDir("nacional");

        // Act
        var (rules, _, _) = ProviderConfigGenerator.GenerateFromXsdFiles(xsdDir, "nacional");

        // Assert
        var conditionalRules = rules
            .Where(r => r.Type == RuleType.ConditionalEmission)
            .ToList();

        var duplicates = conditionalRules
            .GroupBy(r => r.Target)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToList();

        duplicates.ShouldBeEmpty(
            $"ConditionalEmission rules should not have duplicate targets. " +
            $"Duplicates: {string.Join(", ", duplicates)}");
    }

    // ==========================================================
    // GISSOnline schema -- CPF/CNPJ choice rules
    // ==========================================================

    [Fact]
    public void Given_GissonlineSchema_Should_GenerateCpfCnpjRulesForCpfCnpjChoice()
    {
        // Arrange
        var xsdDir = TestProviderPaths.FindXsdDir("gissonline");

        // Act
        var (rules, _, _) = ProviderConfigGenerator.GenerateFromXsdFiles(xsdDir, "gissonline");

        // Assert
        var conditionalRules = rules
            .Where(r => r.Type == RuleType.ConditionalEmission)
            .ToList();

        // GISSOnline has tcCpfCnpj complex type with choice between Cpf and Cnpj.
        // The auto-gen should detect this pattern and produce conditional rules.
        var cpfCnpjRules = conditionalRules
            .Where(r => r.Target.Contains("Cpf", StringComparison.OrdinalIgnoreCase) ||
                        r.Target.Contains("Cnpj", StringComparison.OrdinalIgnoreCase))
            .ToList();

        // GISSOnline has CpfCnpj choices in Prestador and in inner types.
        // At minimum we expect the inferrer to produce rules for detected choice groups.
        cpfCnpjRules.Count.ShouldBeGreaterThanOrEqualTo(2,
            "GISSOnline should have at least one CPF and one CNPJ conditional rule from CpfCnpj choice. " +
            $"All conditional targets: {string.Join(", ", conditionalRules.Select(r => r.Target))}");

        // Verify the rules follow the expected structure
        var cnpjRules = cpfCnpjRules
            .Where(r => r.Target.EndsWith("Cnpj", StringComparison.OrdinalIgnoreCase))
            .ToList();
        var cpfRules = cpfCnpjRules
            .Where(r => r.Target.EndsWith("Cpf", StringComparison.OrdinalIgnoreCase))
            .ToList();

        cnpjRules.ShouldNotBeEmpty("Should have CNPJ conditional rules from CpfCnpj choice");
        cpfRules.ShouldNotBeEmpty("Should have CPF conditional rules from CpfCnpj choice");

        // Each CNPJ rule uses GreaterThan 99999999999 comparison
        foreach (var cnpjRule in cnpjRules)
        {
            cnpjRule.Condition.ShouldNotBeNull();
            cnpjRule.Condition!.Operator.ShouldBe(ComparisonOperator.GreaterThan);
            cnpjRule.Condition.Value.ShouldBe("99999999999");
            cnpjRule.PadLeft.ShouldBe(14);
        }

        // Each CPF rule uses composite AND condition
        foreach (var cpfRule in cpfRules)
        {
            cpfRule.Condition.ShouldNotBeNull();
            cpfRule.Condition!.IsComposite.ShouldBeTrue(
                $"CPF rule for '{cpfRule.Target}' should use composite AND condition");
            cpfRule.PadLeft.ShouldBe(11);
        }
    }

    // ==========================================================
    // ABRASF schema -- choice rules without duplicating wrapper bindings
    // ==========================================================

    [Fact]
    public void Given_AbrasfSchema_Should_GenerateChoiceRulesWithoutDuplicatingWrapperBindings()
    {
        // Arrange
        var xsdDir = TestProviderPaths.FindXsdDir("abrasf");

        // Act
        var (rules, profile, _) = ProviderConfigGenerator.GenerateFromXsdFiles(xsdDir, "abrasf");

        // Assert
        var conditionalRules = rules
            .Where(r => r.Type == RuleType.ConditionalEmission)
            .ToList();

        // ABRASF schema has tcCpfCnpj choice inside tcIdentificacaoPessoaEmpresa.
        // Auto-gen should produce conditional rules for the CPF/CNPJ choice,
        // and those rules should NOT overlap with wrapper bindings.
        var wrapperTargets = profile.WrapperBindings?.Keys.ToHashSet(StringComparer.OrdinalIgnoreCase)
                             ?? new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var rule in conditionalRules)
        {
            wrapperTargets.ShouldNotContain(rule.Target,
                $"ConditionalEmission rule target '{rule.Target}' should not duplicate a wrapper binding");
        }

        // Verify no duplicate targets within conditional rules themselves
        var duplicateTargets = conditionalRules
            .GroupBy(r => r.Target)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToList();
        duplicateTargets.ShouldBeEmpty(
            $"ABRASF ConditionalEmission rules should not have duplicate targets. " +
            $"Duplicates: {string.Join(", ", duplicateTargets)}");
    }

    // ==========================================================
    // ISSNet config -- regression: preserve existing behavior
    // ==========================================================

    [Fact]
    public void Given_IssnetConfig_Should_PreserveExistingBehavior()
    {
        // Arrange
        var providersDir = TestProviderPaths.FindProvidersDir();
        var rulesPath = Path.Combine(providersDir, "issnet", "rules", "rules.json");

        // Act -- load the manually curated rules.json
        var manualProfile = ProviderProfile.LoadFromFile(rulesPath);

        // Assert -- the manual config should exist and have the expected structure
        manualProfile.ShouldNotBeNull("ISSNet rules.json should exist");
        manualProfile!.Provider.ShouldBe("issnet");
        manualProfile.BindingPathPrefix.ShouldBe("LoteDps.ListaDps.DPS",
            "ISSNet bindingPathPrefix should remain unchanged");
        manualProfile.WrapperBindings.ShouldNotBeNull();
        manualProfile.WrapperBindings!.Count.ShouldBeGreaterThan(0,
            "ISSNet should have wrapper bindings for envelope");

        // Verify auto-gen for issnet does not break -- it should produce a valid profile
        var generator = new ProviderConfigGenerator(providersDir);
        var generatedProfile = generator.GenerateConfig("issnet");
        generatedProfile.ShouldNotBeNull();
        generatedProfile.Provider.ShouldBe("issnet");

        // ISSNet may or may not produce auto-gen rules depending on schema structure.
        // The key assertion is that it does not throw and preserves the manual config structure.
        if (generatedProfile.Rules is { Count: > 0 })
        {
            var bindingRules = generatedProfile.Rules
                .Where(r => r.Type == RuleType.Binding)
                .ToList();
            bindingRules.ShouldNotBeEmpty("ISSNet auto-gen should produce binding rules when rules exist");
        }
    }

    // ==========================================================
    // Nacional schema -- auto-gen CPF/CNPJ matches manual rules structure
    // ==========================================================

    [Fact]
    public void Given_NacionalSchema_AutoGenCpfCnpjRules_Should_MatchManualRulesStructure()
    {
        // Arrange
        var providersDir = TestProviderPaths.FindProvidersDir();
        var manualProfile = ProviderProfile.LoadFromFile(
            Path.Combine(providersDir, "nacional", "rules", "rules.json"));
        manualProfile.ShouldNotBeNull();

        var manualConditionalRules = manualProfile!.Rules!
            .Where(r => r.Type == RuleType.ConditionalEmission)
            .ToList();

        var xsdDir = TestProviderPaths.FindXsdDir("nacional");

        // Act
        var (autoGenRules, _, _) = ProviderConfigGenerator.GenerateFromXsdFiles(xsdDir, "nacional");

        // Assert -- auto-gen should produce CPF/CNPJ rules that structurally match manual ones
        var autoGenConditionalRules = autoGenRules
            .Where(r => r.Type == RuleType.ConditionalEmission)
            .ToList();

        // For each manual CPF/CNPJ ConditionalEmission rule on toma,
        // verify there is a structurally equivalent auto-generated rule
        foreach (var manualRule in manualConditionalRules)
        {
            // Only check toma CPF/CNPJ rules (the ones the inferrer produces)
            if (!manualRule.Target.Contains("toma", StringComparison.OrdinalIgnoreCase))
                continue;
            if (!manualRule.Target.EndsWith("CNPJ") && !manualRule.Target.EndsWith("CPF"))
                continue;

            // Find the matching auto-gen rule by target suffix
            var targetSuffix = manualRule.Target.EndsWith("CNPJ") ? "CNPJ" : "CPF";
            var autoGenMatch = autoGenConditionalRules.FirstOrDefault(r =>
                r.Target.Contains("toma", StringComparison.OrdinalIgnoreCase) &&
                r.Target.EndsWith(targetSuffix));

            autoGenMatch.ShouldNotBeNull(
                $"Auto-gen should produce a rule matching manual target pattern '{manualRule.Target}'. " +
                $"Auto-gen targets: {string.Join(", ", autoGenConditionalRules.Select(r => r.Target))}");

            // Verify structural equivalence
            autoGenMatch!.Action.ShouldBe(manualRule.Action,
                $"Action mismatch for {targetSuffix} rule");
            autoGenMatch.PadLeft.ShouldBe(manualRule.PadLeft,
                $"PadLeft mismatch for {targetSuffix} rule");
            autoGenMatch.PadChar.ShouldBe(manualRule.PadChar,
                $"PadChar mismatch for {targetSuffix} rule");

            // Verify condition uses the same field
            autoGenMatch.Condition.ShouldNotBeNull();
            if (manualRule.Condition!.IsComposite)
            {
                autoGenMatch.Condition!.IsComposite.ShouldBeTrue(
                    $"Auto-gen {targetSuffix} rule should have composite condition like manual");
                autoGenMatch.Condition.LogicalOperator.ShouldBe(manualRule.Condition.LogicalOperator);
            }
            else
            {
                autoGenMatch.Condition!.Field.ShouldBe(manualRule.Condition.Field);
                autoGenMatch.Condition.Operator.ShouldBe(manualRule.Condition.Operator);
                autoGenMatch.Condition.Value.ShouldBe(manualRule.Condition.Value);
            }
        }
    }

    // ==========================================================
    // Nacional schema -- provider context (prest) CPF/CNPJ rules
    // ==========================================================

    [Fact]
    public void Given_NacionalSchema_Should_GenerateCpfCnpjRulesForPrestadorContext()
    {
        // Arrange
        var xsdDir = TestProviderPaths.FindXsdDir("nacional");

        // Act
        var (rules, _, _) = ProviderConfigGenerator.GenerateFromXsdFiles(xsdDir, "nacional");

        // Assert
        var conditionalRules = rules
            .Where(r => r.Type == RuleType.ConditionalEmission)
            .ToList();

        // The prest (provider) context also has a CNPJ/CPF choice in the Nacional schema.
        // Check that at least the prest context has a CNPJ rule with Provider.Cnpj source
        // (the prest CPF/CNPJ elements are in contextual mappings, handled differently)
        var prestCnpjRule = conditionalRules.FirstOrDefault(r =>
            r.Target.Contains("prest", StringComparison.OrdinalIgnoreCase) &&
            r.Target.EndsWith("CNPJ", StringComparison.OrdinalIgnoreCase));

        // Note: prest.CNPJ may be handled as a regular binding (since CNPJ mapping
        // exists in ContextualMappings["prest"]) rather than a conditional rule.
        // This test verifies the overall rule set covers the prest context.
        var prestBindingOrConditional = rules.Any(r =>
            r.Target.Contains("prest", StringComparison.OrdinalIgnoreCase) &&
            r.Target.EndsWith("CNPJ", StringComparison.OrdinalIgnoreCase));

        prestBindingOrConditional.ShouldBeTrue(
            "Nacional should have a binding or conditional rule covering prest.CNPJ. " +
            $"All rule targets: {string.Join(", ", rules.Select(r => r.Target))}");
    }

    // ==========================================================
    // Nacional schema -- conditional rules do not conflict with binding rules
    // ==========================================================

    [Fact]
    public void Given_NacionalSchema_Should_NotProduceConflictingBindingAndConditionalRulesForSameTarget()
    {
        // Arrange
        var xsdDir = TestProviderPaths.FindXsdDir("nacional");

        // Act
        var (rules, _, _) = ProviderConfigGenerator.GenerateFromXsdFiles(xsdDir, "nacional");

        // Assert
        var conditionalTargets = rules
            .Where(r => r.Type == RuleType.ConditionalEmission)
            .Select(r => r.Target)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var bindingTargets = rules
            .Where(r => r.Type == RuleType.Binding)
            .Select(r => r.Target)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        var conflicts = conditionalTargets
            .Intersect(bindingTargets, StringComparer.OrdinalIgnoreCase)
            .ToList();

        conflicts.ShouldBeEmpty(
            $"No target should have both a Binding and ConditionalEmission rule. " +
            $"Conflicts: {string.Join(", ", conflicts)}");
    }
}
