using System.Globalization;
using System.Text;

namespace SemanaIA.ServiceInvoice.XmlGeneration.SchemaEngine;

public class SchemaCodeGenerator
{
    private const string AutoGeneratedHeader = "// Auto-generated from XSD schema. Do not edit manually.";
    private const string DefaultNamespace = "SemanaIA.ServiceInvoice.XmlGeneration.Generated";

    private static readonly Dictionary<string, string> XsdToCSharpTypeMap = new()
    {
        ["string"] = "string?",
        ["decimal"] = "decimal?",
        ["int"] = "int?",
        ["long"] = "long?",
        ["boolean"] = "bool?",
        ["date"] = "DateOnly?",
        ["dateTime"] = "DateTimeOffset?",
        ["positiveInteger"] = "int?",
        ["nonNegativeInteger"] = "int?"
    };

    public void GenerateRecords(SchemaDocument schema, string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        foreach (var ct in schema.ComplexTypes)
        {
            var code = GenerateRecord(ct, schema.TargetNamespace);
            var fileName = $"{ct.Name}.cs";
            File.WriteAllText(Path.Combine(outputDir, fileName), code);
        }
    }

    public void GenerateBuilderSkeleton(
        SchemaDocument schema,
        IProviderRuleResolver resolver,
        string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        var code = GenerateBuilderClass(schema, resolver);
        File.WriteAllText(Path.Combine(outputDir, "NacionalDpsBuilderSkeleton.cs"), code);
    }

    public string GenerateComparisonReport(SchemaDocument schema, string manualSerializerPath)
    {
        var manualContent = File.Exists(manualSerializerPath)
            ? File.ReadAllText(manualSerializerPath)
            : string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("# Comparison Report: Generated vs. Manual Baseline");
        sb.AppendLine();
        sb.AppendLine($"**Schema complex types:** {schema.ComplexTypes.Count}");
        sb.AppendLine($"**Manual serializer:** `{Path.GetFileName(manualSerializerPath)}`");
        sb.AppendLine();
        sb.AppendLine("| ComplexType | In Manual? | Build* Method | Elements (XSD) | Notes |");
        sb.AppendLine("|------------|-----------|---------------|----------------|-------|");

        foreach (var ct in schema.ComplexTypes)
        {
            var buildMethod = FindBuildMethod(ct.Name, manualContent);
            var inManual = buildMethod is not null ? "yes" : "no";
            var elementCount = ct.Elements.Count;
            sb.AppendLine($"| {ct.Name} | {inManual} | {buildMethod ?? "-"} | {elementCount} | |");
        }

        return sb.ToString();
    }

    // --- Private methods ---

    private static string GenerateRecord(SchemaComplexType ct, string targetNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine($"// Source: {ct.Name} from {targetNamespace}");
        sb.AppendLine();
        sb.AppendLine($"namespace {DefaultNamespace};");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(ct.Annotation))
            sb.AppendLine($"/// <summary>{ct.Annotation}</summary>");

        sb.AppendLine($"public record {ct.Name}(");

        for (var i = 0; i < ct.Elements.Count; i++)
        {
            var el = ct.Elements[i];
            var csharpType = MapXsdType(el.TypeName, el.IsRequired);
            var propName = ToPascalCase(el.Name);
            var separator = i < ct.Elements.Count - 1 ? "," : ");";
            var choiceComment = el.IsChoice ? $" // choice: {el.ChoiceGroup}" : "";

            sb.AppendLine($"    {csharpType} {propName}{separator}{choiceComment}");
        }

        return sb.ToString();
    }

    private static string GenerateBuilderClass(SchemaDocument schema, IProviderRuleResolver resolver)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedHeader);
        sb.AppendLine($"// Provider: nacional | Namespace: {schema.TargetNamespace}");
        sb.AppendLine();
        sb.AppendLine($"namespace {DefaultNamespace};");
        sb.AppendLine();
        sb.AppendLine("public class NacionalDpsBuilderSkeleton");
        sb.AppendLine("{");

        foreach (var ct in schema.ComplexTypes)
        {
            sb.AppendLine($"    // --- {ct.Name} ---");
            sb.AppendLine();
            sb.AppendLine($"    public void Build{ct.Name}(dynamic xml)");
            sb.AppendLine("    {");

            foreach (var el in ct.Elements)
            {
                var formatting = resolver.ResolveFormatting(el.Name);
                var conditional = resolver.GetConditionalExpression(el.Name);

                if (conditional is not null)
                    sb.AppendLine($"        // conditional: {conditional}");

                if (el.IsChoice)
                    sb.AppendLine($"        // choice: {el.ChoiceGroup}");

                if (formatting is not null)
                {
                    var notes = new List<string>();
                    if (formatting.PadLeft.HasValue)
                        notes.Add($"padLeft({formatting.PadLeft}, '{formatting.PadChar ?? "0"}')");
                    if (formatting.DigitsOnly == true)
                        notes.Add("digitsOnly");
                    if (formatting.MaxLength.HasValue)
                        notes.Add($"maxLength({formatting.MaxLength})");
                    if (formatting.RemoveChars is not null)
                        notes.Add($"removeChars(\"{formatting.RemoveChars}\")");

                    sb.AppendLine($"        // formatting: {string.Join(", ", notes)}");
                }

                var requiredComment = el.IsRequired ? "" : " // optional";
                sb.AppendLine($"        xml.{el.Name}(/* {el.TypeName} */);{requiredComment}");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string MapXsdType(string xsdType, bool isRequired)
    {
        if (XsdToCSharpTypeMap.TryGetValue(xsdType, out var mapped))
            return isRequired ? mapped.TrimEnd('?') : mapped;

        return isRequired ? "object" : "object?";
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToUpper(name[0], CultureInfo.InvariantCulture) + name[1..];
    }

    private static string? FindBuildMethod(string complexTypeName, string sourceCode)
    {
        if (string.IsNullOrEmpty(sourceCode)) return null;

        var mappings = new Dictionary<string, string>
        {
            ["TCInfoPrestador"] = "BuildProvider",
            ["TCInfoPessoa"] = "BuildPerson",
            ["TCEndereco"] = "BuildEndereco",
            ["TCEnderNac"] = "BuildEndereco",
            ["TCEnderExt"] = "BuildEndereco",
            ["TCServ"] = "BuildServico",
            ["TCLocPrest"] = "BuildLocPrest",
            ["TCCServ"] = "BuildCServ",
            ["TCComExterior"] = "BuildComExt",
            ["TCLocacaoSublocacao"] = "BuildLsadppu",
            ["TCInfoObra"] = "BuildObra",
            ["TCAtvEvento"] = "BuildAtvEvento",
            ["TCInfoCompl"] = "BuildInfoCompl",
            ["TCInfoValores"] = "BuildValores",
            ["TCTribMunicipal"] = "BuildTribMun",
            ["TCTribFederal"] = "BuildTribFed",
            ["TCTribTotal"] = "BuildTotTrib",
            ["TCRegTrib"] = "BuildRegTrib",
            ["TCInfDPS"] = "BuildInfDps",
            ["TCDPS"] = "Serialize",
            ["TCRTCInfoIBSCBS"] = "BuildIbsCbs",
            ["TCVServPrest"] = "BuildValores",
            ["TCVDescCondIncond"] = "BuildValores",
            ["TCInfoDedRed"] = "BuildValores",
            ["TCInfoTributacao"] = "BuildValores",
            ["TCExigSuspensa"] = "BuildTribMun",
            ["TCBeneficioMunicipal"] = "BuildTribMun",
            ["TCTribOutrosPisCofins"] = "BuildTribFed"
        };

        if (mappings.TryGetValue(complexTypeName, out var methodName))
            return sourceCode.Contains(methodName) ? methodName : null;

        return null;
    }
}
