using System.Xml.Linq;
using SemanaIA.ServiceInvoice.Domain.Models;
using SemanaIA.ServiceInvoice.UnitTests.Manual;
using SemanaIA.ServiceInvoice.XmlGeneration.Manual;
using SemanaIA.ServiceInvoice.UnitTests.SchemaEngine;
using SemanaIA.ServiceInvoice.XmlGeneration.SchemaEngine;
using Shouldly;
using Xunit.Abstractions;

namespace SemanaIA.ServiceInvoice.UnitTests.Snapshots;

/// <summary>
/// Compares XML generated by the manual serializer (XBuilder) vs the schema engine
/// for the same input data. Both should produce structurally equivalent XML.
/// </summary>
public class ManualVsEngineComparisonTests
{
    private readonly ITestOutputHelper _output;
    private readonly NationalDpsManualSerializer _manualSerializer = new();

    public ManualVsEngineComparisonTests(ITestOutputHelper output)
    {
        _output = output;
    }

    [Fact]
    public void Given_MinimalDocument_Should_ProduceEquivalentXml()
    {
        // Arrange
        var document = CreateDocumentWithProviderData();

        // Act — Manual serializer
        var manualResult = _manualSerializer.Serialize(document);
        manualResult.Xml.ShouldNotBeNull("Manual serializer should produce XML");

        // Act — Schema engine (simulating the API flow)
        var engineXml = GenerateViaSchemaEngine(document);

        // Assert — both produced XML
        engineXml.ShouldNotBeNull("Schema engine should produce XML");

        // Compare structure
        var manualDoc = XDocument.Parse(manualResult.Xml);
        var engineDoc = XDocument.Parse(engineXml);

        var manualRoot = manualDoc.Root!;
        var engineRoot = engineDoc.Root!;

        // Root element should be the same
        manualRoot.Name.LocalName.ShouldBe(engineRoot.Name.LocalName,
            "Root element name should match");

        // Compare key child elements
        var ns = manualRoot.Name.Namespace;
        var manualInfDps = manualRoot.Element(ns + "infDPS");
        var engineInfDps = engineRoot.Element(ns + "infDPS");

        manualInfDps.ShouldNotBeNull("Manual should have infDPS");
        engineInfDps.ShouldNotBeNull("Engine should have infDPS");

        // Compare specific elements that both should produce
        CompareElement(manualInfDps, engineInfDps, ns, "tpAmb");
        CompareElement(manualInfDps, engineInfDps, ns, "dhEmi");
        CompareElement(manualInfDps, engineInfDps, ns, "verAplic");
        CompareElement(manualInfDps, engineInfDps, ns, "serie");
        CompareElement(manualInfDps, engineInfDps, ns, "nDPS");
        CompareElement(manualInfDps, engineInfDps, ns, "dCompet");
        CompareElement(manualInfDps, engineInfDps, ns, "tpEmit");
        CompareElement(manualInfDps, engineInfDps, ns, "cLocEmi");

        // Report differences
        _output.WriteLine("=== Manual XML (first 500 chars) ===");
        _output.WriteLine(manualResult.Xml[..Math.Min(500, manualResult.Xml.Length)]);
        _output.WriteLine("\n=== Engine XML (first 500 chars) ===");
        _output.WriteLine(engineXml[..Math.Min(500, engineXml.Length)]);

        // Count elements in each
        var manualElements = manualInfDps.Descendants().Count();
        var engineElements = engineInfDps.Descendants().Count();
        _output.WriteLine($"\nManual elements: {manualElements}, Engine elements: {engineElements}");
    }

    // --- Private methods ---

    private static DpsDocument CreateDocumentWithProviderData()
    {
        var doc = DpsDocumentTestFixture.CreateValidMinimal();
        // Add provider data that the engine needs
        doc.Provider.Cnpj = "12345678000199";
        doc.Provider.FederalTaxNumber = 12345678000199;
        doc.Provider.MunicipalTaxNumber = "12345678";
        doc.Provider.TaxRegime = TaxRegime.SimplesNacional;
        doc.Provider.Address = new Address
        {
            Country = "BRA",
            PostalCode = "01000-000",
            Street = "RUA DO PRESTADOR",
            Number = "500",
            District = "CENTRO",
            City = new City { Code = "3550308" },
            State = "SP"
        };
        return doc;
    }

    private static string? GenerateViaSchemaEngine(DpsDocument document)
    {
        var providersBaseDir = TestProviderPaths.FindProvidersDir();
        var xsdDir = TestProviderPaths.FindXsdDir("nacional");
        var selector = new SendXsdSelector();
        var selection = selector.Select(xsdDir);

        if (selection.SelectedFile is null)
            return null;

        var analyzer = new XsdSchemaAnalyzer();
        var schema = analyzer.Analyze(selection.SelectedFile);

        var profile = ProviderProfile.LoadFromFile(
            Path.Combine(providersBaseDir, "nacional", "rules", "rules.json"))
            ?? ProviderProfile.LoadFromFile(
                Path.Combine(providersBaseDir, "nacional", "rules", "base-rules.json"))
            ?? new ProviderProfile();

        var binder = new ServiceInvoiceSchemaDataBinder();
        var boundData = binder.Bind(document, profile, schema);

        var resolver = new TypedRuleResolver(profile.Rules ?? []);
        var rootType = profile.RootComplexTypeName ?? "TCDPS";
        var rootElement = profile.RootElementName ?? "DPS";

        var serializer = new SchemaBasedXmlSerializer();
        var result = serializer.Serialize(schema, boundData, resolver, rootType, rootElement, profile.Version);

        return result.Xml;
    }

    private void CompareElement(XElement manualParent, XElement engineParent, XNamespace ns, string elementName)
    {
        var manualEl = manualParent.Element(ns + elementName);
        var engineEl = engineParent.Element(ns + elementName);

        if (manualEl is null && engineEl is null)
            return;

        if (manualEl is not null && engineEl is null)
        {
            _output.WriteLine($"[DIFF] <{elementName}> exists in manual but missing in engine");
            return;
        }

        if (manualEl is null && engineEl is not null)
        {
            _output.WriteLine($"[DIFF] <{elementName}> exists in engine but missing in manual");
            return;
        }

        if (manualEl!.Value != engineEl!.Value)
        {
            _output.WriteLine($"[DIFF] <{elementName}> manual='{manualEl.Value}' engine='{engineEl.Value}'");
        }
        else
        {
            _output.WriteLine($"[MATCH] <{elementName}> = '{manualEl.Value}'");
        }
    }
}
