using System.Xml.Linq;
using SemanaIA.ServiceInvoice.Domain.Models;
using SemanaIA.ServiceInvoice.UnitTests.Manual;
using SemanaIA.ServiceInvoice.UnitTests.SchemaEngine;
using SemanaIA.ServiceInvoice.XmlGeneration.Manual;
using SemanaIA.ServiceInvoice.XmlGeneration.SchemaEngine;
using Shouldly;
using Xunit.Abstractions;

namespace SemanaIA.ServiceInvoice.UnitTests.Snapshots;

/// <summary>
/// Compares XML generated by the manual serializer (XBuilder/production) vs the schema engine
/// for the same input data. The manual serializer is the source of truth (validated in production).
/// The engine must produce the same elements — no more, no less.
/// </summary>
public class ManualVsEngineComparisonTests
{
    private readonly ITestOutputHelper _output;
    private readonly NationalDpsManualSerializer _manualSerializer = new();

    public ManualVsEngineComparisonTests(ITestOutputHelper output)
    {
        _output = output;
    }

    [Fact]
    public void Given_MinimalDocument_ManualAndEngine_Should_ProduceIdenticalElements()
    {
        // Arrange
        var document = CreateDocumentWithProviderData();

        // Act — Manual serializer (production, source of truth)
        var manualResult = _manualSerializer.Serialize(document);
        manualResult.Xml.ShouldNotBeNull("Manual serializer should produce XML");

        // Act — Schema engine using AUTO-GEN rules (same flow as API POST /providers)
        var engineXml = GenerateViaAutoGen(document);
        engineXml.ShouldNotBeNull("Schema engine should produce XML");

        // Parse both
        var manualDoc = XDocument.Parse(manualResult.Xml);
        var engineDoc = XDocument.Parse(engineXml);

        // Collect all element paths from both
        var manualPaths = CollectElementPaths(manualDoc.Root!, "").OrderBy(p => p).ToList();
        var enginePaths = CollectElementPaths(engineDoc.Root!, "").OrderBy(p => p).ToList();

        // Report elements only in manual (engine missing)
        var onlyInManual = manualPaths.Except(enginePaths).ToList();
        var onlyInEngine = enginePaths.Except(manualPaths).ToList();

        _output.WriteLine($"Manual elements: {manualPaths.Count}, Engine elements: {enginePaths.Count}");
        _output.WriteLine($"Only in manual: {onlyInManual.Count}, Only in engine: {onlyInEngine.Count}");

        if (onlyInManual.Count > 0)
        {
            _output.WriteLine("\n=== MISSING IN ENGINE (manual has, engine doesn't) ===");
            foreach (var path in onlyInManual)
                _output.WriteLine($"  [-] {path}");
        }

        if (onlyInEngine.Count > 0)
        {
            _output.WriteLine("\n=== PHANTOM IN ENGINE (engine has, manual doesn't) ===");
            foreach (var path in onlyInEngine)
                _output.WriteLine($"  [+] {path}");
        }

        // Compare values of shared elements
        _output.WriteLine("\n=== VALUE COMPARISON (shared elements) ===");
        var sharedPaths = manualPaths.Intersect(enginePaths).ToList();
        var valueDiffs = new List<string>();
        foreach (var path in sharedPaths)
        {
            var manualValue = GetElementValue(manualDoc.Root!, path);
            var engineValue = GetElementValue(engineDoc.Root!, path);
            if (manualValue != engineValue)
            {
                valueDiffs.Add($"{path}: manual='{manualValue}' engine='{engineValue}'");
                _output.WriteLine($"  [DIFF] {path}: manual='{manualValue}' engine='{engineValue}'");
            }
        }

        // Assert — shared elements must have identical values
        valueDiffs.ShouldBeEmpty(
            $"Engine produced {valueDiffs.Count} element(s) with differing values:\n{string.Join("\n", valueDiffs)}");

        // Assert — engine must not have phantom elements
        onlyInEngine.ShouldBeEmpty(
            $"Engine produces {onlyInEngine.Count} phantom element(s) not in manual:\n{string.Join("\n", onlyInEngine)}");

        // Assert — engine must have all manual elements
        onlyInManual.ShouldBeEmpty(
            $"Engine missing {onlyInManual.Count} element(s) from manual:\n{string.Join("\n", onlyInManual)}");
    }

    [Fact]
    public void Given_MinimalDocument_WithFilesystemRules_Should_ProduceEquivalentXml()
    {
        // Arrange — uses rules.json from filesystem (manually configured, more complete)
        var document = CreateDocumentWithProviderData();

        // Act
        var manualResult = _manualSerializer.Serialize(document);
        var engineXml = GenerateViaFilesystemRules(document);

        // Assert — both produce XML
        manualResult.Xml.ShouldNotBeNull();
        engineXml.ShouldNotBeNull();

        _output.WriteLine("=== Manual XML ===");
        _output.WriteLine(XDocument.Parse(manualResult.Xml).ToString());
        _output.WriteLine("\n=== Engine XML (filesystem rules) ===");
        _output.WriteLine(XDocument.Parse(engineXml).ToString());

        var manualDoc = XDocument.Parse(manualResult.Xml);
        var engineDoc = XDocument.Parse(engineXml);
        _output.WriteLine($"\nManual: {manualDoc.Root!.Descendants().Count()}, Engine: {engineDoc.Root!.Descendants().Count()}");

        // Structural element-path equivalence (element paths must match)
        var manualPaths = CollectElementPaths(manualDoc.Root!, "").OrderBy(p => p).ToList();
        var enginePaths = CollectElementPaths(engineDoc.Root!, "").OrderBy(p => p).ToList();
        var onlyInManual = manualPaths.Except(enginePaths).ToList();
        var onlyInEngine = enginePaths.Except(manualPaths).ToList();

        onlyInEngine.ShouldBeEmpty(
            $"Engine has {onlyInEngine.Count} phantom element(s):\n{string.Join("\n", onlyInEngine)}");
    }

    // --- Private methods ---

    private static DpsDocument CreateDocumentWithProviderData()
    {
        var doc = DpsDocumentTestFixture.CreateValidMinimal();
        doc.Provider.Cnpj = "12345678000199";
        doc.Provider.FederalTaxNumber = 12345678000199;
        doc.Provider.MunicipalTaxNumber = "12345678";
        doc.Provider.TaxRegime = TaxRegime.SimplesNacional;
        doc.Provider.Address = new Address
        {
            Country = "BRA",
            PostalCode = "01000-000",
            Street = "RUA DO PRESTADOR",
            Number = "500",
            District = "CENTRO",
            City = new City { Code = "3550308" },
            State = "SP"
        };
        return doc;
    }

    private static string? GenerateViaAutoGen(DpsDocument document)
    {
        var xsdDir = TestProviderPaths.FindXsdDir("nacional");
        var selector = new SendXsdSelector();
        var selection = selector.Select(xsdDir);

        if (selection.SelectedFile is null)
            return null;

        // Auto-gen rules — same flow as ProviderManagementService.Create
        var (rules, profile, _) = ProviderConfigGenerator.GenerateFromXsdFiles(
            xsdDir, "nacional", selection.SelectedFile);
        profile.Rules = rules;

        var analyzer = new XsdSchemaAnalyzer();
        var schema = analyzer.Analyze(selection.SelectedFile);

        var binder = new ServiceInvoiceSchemaDataBinder();
        var boundData = binder.Bind(document, profile, schema);

        var resolver = new TypedRuleResolver(profile.Rules ?? []);
        var rootType = profile.RootComplexTypeName ?? "TCDPS";
        var rootElement = profile.RootElementName ?? "DPS";

        var serializer = new SchemaBasedXmlSerializer();
        var result = serializer.Serialize(schema, boundData, resolver, rootType, rootElement, profile.Version);

        return result.Xml;
    }

    private static string? GenerateViaFilesystemRules(DpsDocument document)
    {
        var providersBaseDir = TestProviderPaths.FindProvidersDir();
        var xsdDir = TestProviderPaths.FindXsdDir("nacional");
        var selector = new SendXsdSelector();
        var selection = selector.Select(xsdDir);

        if (selection.SelectedFile is null)
            return null;

        var analyzer = new XsdSchemaAnalyzer();
        var schema = analyzer.Analyze(selection.SelectedFile);

        var profile = ProviderProfile.LoadFromFile(
            Path.Combine(providersBaseDir, "nacional", "rules", "rules.json"))
            ?? ProviderProfile.LoadFromFile(
                Path.Combine(providersBaseDir, "nacional", "rules", "base-rules.json"))
            ?? new ProviderProfile();

        var binder = new ServiceInvoiceSchemaDataBinder();
        var boundData = binder.Bind(document, profile, schema);

        var resolver = new TypedRuleResolver(profile.Rules ?? []);
        var rootType = profile.RootComplexTypeName ?? "TCDPS";
        var rootElement = profile.RootElementName ?? "DPS";

        var serializer = new SchemaBasedXmlSerializer();
        var result = serializer.Serialize(schema, boundData, resolver, rootType, rootElement, profile.Version);

        return result.Xml;
    }

    private static List<string> CollectElementPaths(XElement root, string prefix)
    {
        var paths = new List<string>();
        var path = string.IsNullOrEmpty(prefix)
            ? root.Name.LocalName
            : $"{prefix}/{root.Name.LocalName}";

        if (!root.HasElements)
        {
            paths.Add(path);
        }
        else
        {
            foreach (var child in root.Elements())
                paths.AddRange(CollectElementPaths(child, path));
        }

        return paths;
    }

    private static string? GetElementValue(XElement root, string elementPath)
    {
        var segments = elementPath.Split('/');
        XElement? current = root;

        // Skip root element name
        foreach (var segment in segments.Skip(1))
        {
            current = current?.Elements().FirstOrDefault(e => e.Name.LocalName == segment);
        }

        return current?.Value;
    }
}
